# Generated by Django 4.2.23 on 2025-07-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Entertainment', 'Entertainment'), ('Productivity', 'Productivity'), ('Gaming', 'Gaming'), ('E-commerce', 'E-commerce'), ('Other', 'Other')], default='Other', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
